source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'pod_library_test_Example', :exclusive => true do
  pod "pod_library_test", :path => "../"
end

target 'pod_library_test_Tests', :exclusive => true do
  pod "pod_library_test", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
